export const labels = {
  usage: { sns:'SNS図解', product:'商品・サービス紹介', proposal:'1枚提案書', sales:'営業資料', compare:'比較資料', guide:'初心者向け解説' },
  layout: { grid:'一覧で見せる', flow:'順番で見せる', relation:'関係を見せる', compare:'比べて見せる', problem:'困りごとから提案する' },
  design: { simple:'すっきり・読みやすい', friendly:'やさしく親しみやすい', energetic:'明るく元気', professional:'信頼感のある', handdrawn:'手描き風であたたかい' },
  density: { light:'情報を絞って余白を広く', balanced:'大切な情報をバランスよく', rich:'情報をしっかり載せる' }
};
export const createPromptModel=(o={})=>({version:1,usage:'',layout:'',design:'',density:'',topic:'',mustInclude:'',other:'',characterEnabled:false,characterMode:'',character:'',adapter:'',...o});
function knownLines(m){return[(m.topic.trim()&&'資料テーマ：'+m.topic.trim()),m.usage&&'資料の用途：'+labels.usage[m.usage],m.layout&&'資料の構成：'+labels.layout[m.layout],m.design&&'資料のデザイン：'+labels.design[m.design],m.density&&'情報量：'+labels.density[m.density],m.mustInclude&&'追加内容：'+m.mustInclude,m.other&&'その他：'+m.other,m.characterMode==='person'&&'人物：'+(m.character||'人物を使う'),m.characterMode==='same'&&'人物：同じキャラクターを使う',m.characterMode==='sheet'&&'人物：添付されたキャラクターシートを基準にする'].filter(Boolean)}
const shared=['A4横サイズの1枚資料を作成してください。','ユーザーが入力・選択していない目的、対象者、伝えたい内容、数字、料金、メリット、注意事項、CTA、具体例を勝手に補完しないでください。','ユーザーが選択した資料用途、資料構成、資料デザイン、情報量を優先してください。','ステップ数や項目数をユーザーが指定していない場合、必ず3ステップなどと固定しないでください。','文字は読みやすく、要素を詰め込みすぎず、A4一枚に収めてください。'];
const chatgpt=['上記の情報はユーザーが指定済みのため、同じ内容を再質問しないでください。','資料作成に必要な情報が不足している場合のみ、ユーザーへ確認してください。','確認は一度に1問だけにし、原則3〜5個の選択肢と「その他」を提示してください。番号だけでも回答できる、初心者にも分かる質問にしてください。','必要情報が揃ったら質問を終了し、タイトル、サブタイトル（必要な場合）、対象、目的、各ブロックの内容、図解内容、注意事項、最後の行動案内を整理してください。','整理後に「この内容でA4横の1枚資料を作成しますか？」と確認し、ユーザーが了承してから画像生成を開始してください。'];
const gemini=['この指示文はGeminiの左メニューにある「画像」へ貼り付けて使用してください。','レイアウト案や文章案ではなく、実際のA4横1枚資料の画像を生成してください。','不足情報を質問したり、ユーザーの了承を待ったりせず、入力済みの情報だけでそのまま画像生成してください。','ユーザーが入力・選択していない事実情報を推測して追加しないでください。','割引率、金額、日付、期間、対象地域、対象施設、対象商品、対象者、先着順、枚数制限、数量制限、予約条件、利用条件、キャンペーン条件、料金、メリット、注意事項、具体的なURLやページ名称を根拠なく作らないでください。','不明な情報を埋めるために、もっともらしい数字・制度・条件を創作しないでください。入力されていない事実が必要な場合は、具体的な数字や条件を書かず、一般的な表現にしてください。'];
function characterRules(m){return m.characterMode==='sheet'?['添付されたキャラクターシートを人物デザインの基準にしてください。顔、髪型、服装、色、体格、全体の印象を統一してください。','キャラクターシートが添付されていない場合は「キャラクターシートを添付してください」と案内してください。','キャラクターシートに書かれた説明文や設定資料そのものを完成資料へ転載しないでください。']:[]}
export function buildPrompt(model,adapter=model.adapter){const m=createPromptModel(model);const rules=adapter==='gemini'?gemini:adapter==='chatgpt'?chatgpt:[];const prompt=knownLines(m).concat(shared,rules,characterRules(m)).join('\n');return adapter==='chatgpt'?'ChatGPTへの指示文\n\n'+prompt:adapter==='gemini'?'Gemini「画像」への指示文\n\n'+prompt:prompt}
